### ISSUE TITLE
"Produce PDF Version" opens the .tla file, not the .pdf file on macOS Sierra (10.12.6)

### ISSUE THREAD

**Issue by mkrumhansl** [tlaplus/tlaplus#82] opened 2017-10-06 23:49 UTC
I am working through the TLA+ video course, and selected "Produce PDF Version" for my SimpleProgram module. A new tab opens in the TLA+ Toolbox, but instead of showing the "SimpleProgram.pdf" file, it shows a blank page named "SimpleProgram.tla". See attached image. 
![screen shot 2017-10-06 at 4 36 00 pm](https://user-images.githubusercontent.com/15878654/31302339-e97fb268-aab5-11e7-9988-f299ad7bd5ce.png)

No errors in the logs:
```
!ENTRY org.lamport.tla.toolbox 1 -1 2017-10-06 16:35:00.218
!MESSAGE Spec build invoked on SimpleProgram ...

!ENTRY org.lamport.tla.toolbox 1 -1 2017-10-06 16:35:00.228
!MESSAGE Resulting status is:  parsed 
... build invocation finished.
```

I can browse to the "SimpleProgram.pdf" file in my filesystem and open and view the correctly pretty-printed content. 

Version of TLA+ Toolbox: Version 1.5.4 of 06 October 2017

**Comment by lemmy** [comment] 2017-10-07 08:10
Hi @mkrumhansl 

I'm on 10.13 (High Sierra with yesterday's supplementary update) and can't reproduce the issue. Unfortunately, I don't know how to downgrade to 10.12.6. Do you?

Don't let the title of the view fool you though. Showing the ".tla" file suffix is actually correct.

Technically, the Toolbox embeds "Preview" into the SimpleProgram.tla view. Might it be possible that some setting of yours disabled Preview as the default viewer?

**Comment by quaeler** [comment] 2017-10-08 22:05
I'm on 10.12.6, with 1.5.3, and this works correctly (named ".tla" as well.) Could you try running this against 1.5.3 to see if you still encounter the issue?

**Comment by quaeler** [comment] 2017-10-09 19:51
On 10.12.6 running a development version of 1.5.4, this works correctly for me.

**Comment by mkrumhansl** [comment] 2017-10-09 20:37
@lemmy 
I don't know how to downgrade macOS from High Sierra to Sierra, sorry!
Preview is my default PDF viewer:
<img width="486" alt="screen shot 2017-10-09 at 1 31 37 pm" src="https://user-images.githubusercontent.com/15878654/31357374-47ac4706-acf6-11e7-8d27-9b406d6b7066.png">
I do have a "Back" and "Reload" option when right-clicking in the view, but neither option appears to do anything:
<img width="196" alt="screen shot 2017-10-09 at 1 33 13 pm" src="https://user-images.githubusercontent.com/15878654/31357427-88a4c062-acf6-11e7-8ed7-31c814d1e6ef.png">

@quaeler 
I tried version 1.5.3 of TLA+ Toolbox first before upgrading to the latest development version of 1.5.4. Neither version displays the pdf view correctly for me.

**Comment by lemmy** [comment] 2017-10-09 20:41
@mkrumhansl Is "SimpleProgram.pdf" correctly regenerated when you change the spec, produce the PDF and open it from Finder?

**Comment by mkrumhansl** [comment] 2017-10-09 20:52
Yes, when I change the spec, save, and select "Produce PDF Version" again, the pdf updates correctly.

**Comment by lemmy** [comment] 2017-10-09 20:57
@mkrumhansl Can you send me the complete spec directory?

With 1.5.4 you can also try to temporarily rename "~/.tlaplus/.metadata" to e.g. ".metadata.bak" to have the Toolbox reset to a pristine state. Then create a dummy spec and see if a PDF shows up correctly.

**Comment by mkrumhansl** [comment] 2017-10-10 23:26
@lemmy I attempted to temporarily rename my `~/.tlaplus/.metadata` directory to `~/.tlaplus/.metadata.bak` and this did not fix the issue or change any behavior (besides TLA+ Toolbox forgetting my existing specs and models). 

What does a typical "complete spec directory" look like? What should it contain?

**Comment by lemmy** [comment] 2017-10-11 06:39
@mkrumhansl Right-click the specification in the Spec Explorer > Properties > "Specification root module". Zip the content of that path.

**Comment by lemmy** [comment] 2017-12-04 19:45
@mkrumhansl Are you still stuck with the bug or can we close the issue?

**Comment by mkrumhansl** [comment] 2017-12-04 22:14
You may close it, I am working around this issue by viewing the generated
PDF in a different PDF viewer.

**Closed** 2017-12-05 09:28 UTC
Labels: bug, Toolbox
