### ISSUE TITLE
Configuration files seem to not support negative numbers

### ISSUE THREAD

**Issue by anton-trunov** [tlaplus/tlaplus#508] opened 2020-09-22 15:05 UTC
Here is a minimized .cfg file
```
CONSTANT Foo = -42
```
 that results in the following parsing error
```
Error: TLC threw an unexpected exception.
This was probably caused by an error in the spec or model.
See the User Output or TLC Console for clues to what happened.
The exception was a tlc2.tool.ConfigFileException
: TLC found an error in the configuration file at line 1
It was expecting = or <-, but did not find it.
```

It parses just fine if I remove the minus sign. I guess the workaround here is to use the approach the Toolbox uses with `tla` files and constants with autogenerated names, unfortunately this would complicate my testing setup.

**Comment by lemmy** [comment] 2020-09-22 17:20
What are you proposing?

**Comment by anton-trunov** [comment] 2020-09-22 17:23
It would be great to have negative numbers supported because the configuration file grammar in the "Specifying Systems" book says they are.

**Comment by lemmy** [comment] 2020-09-22 17:33
Can you check if this is a regression?

**Comment by anton-trunov** [comment] 2020-09-23 14:00
I tried using the earliest available on GitHub Toolbox version, but it couldn't make it run on my system.

Looks like the parser treats `-` as a separate token which leads to that error message.I guess like something like this should work: https://github.com/anton-trunov/tlaplus/commit/f04285d85820f18985620b6ca8f702df1dee27b3.

**Comment by lemmy** [comment] 2020-09-23 16:17
```bash
markus@avocado:~/src/TLA/_specs/models/tlcbugs/Github508/Github508.toolbox/Model_1$ java -cp /opt/TLC/tla2tools_1-3-1.jar tlc2.TLC MC
TLC2 Version 2.03 of 10 March 2011
Running in Model-Checking mode.
Error: %1%
Finished. (2020-09-23 09:15:29)

markus@avocado:~/src/TLA/_specs/models/tlcbugs/Github508/Github508.toolbox/Model_1$ java -cp /opt/TLC/tla2tools_1-4-0.jar tlc2.TLC MC
TLC2 Version 2.03 of 20 July 2011
Running in Model-Checking mode.
Error: %1%
Finished. (2020-09-23 09:15:35)
```

**Comment by lemmy** [comment] 2020-09-23 16:42
https://github.com/tlaplus/Examples/blob/848e86637a7b5594089ef8a7ca5b8dc721a160b1/specifications/SpecifyingSystems/TLC/ConfigFileGrammar.tla#L30

**Comment by anton-trunov** [comment] 2020-09-23 17:26
Could you please check if the approach taken in https://github.com/anton-trunov/tlaplus/commit/f04285d85820f18985620b6ca8f702df1dee27b3 is the right one? I can add tests and open a PR if that is the way to go. (I'd probably need a pointer as to where to add tests for `ModelConfig.java`)

**Comment by lemmy** [comment] 2020-09-23 18:48
That hack is too simple because `n = -TRUE` or `n = -"str"` then get accepted by `ModelConfig` and will only be reported during semantic processing.

**Comment by jeenuv** [comment] 2021-02-06 19:49
As an FYI, this doesn't work either, so it's not just when the `-` is at the front:

```
CONSTANT Qty = {1, -1}
```

**Comment by lemmy** [comment] 2021-02-06 19:51
I personally believe https://github.com/tlaplus/tlaplus/issues/578#issuecomment-773413973 should replace the config file.

**Comment by jeenuv** [comment] 2021-02-06 20:05
I don't have a lot of context on the other issue, but drawing from experience from general command line usage, I think in-module annotations create tight coupling.

Right now, there's freedom to run model check with different sets of parameters by keeping them in separate files, and pass them via. `-config` from command line. By embedding parameters as annotations, one has to edit the module source every time, don't they? Or would TLC support Java-style `-Dfoo.bar=baz` on the command line to selectively override them?

**Comment by lemmy** [comment] 2021-02-06 21:20
The `model` module can be in a separate file.

**Comment by lemmy** [comment] 2021-02-06 22:34
Related: https://github.com/tlaplus/tlaplus/issues/577

**Comment by lemmy** [comment] 2021-08-13 23:04
Closing as the config file has never had full support for TLA+ expressions and the workaround is to create an `MC.tla` file.  In addition, the recent work on [IOUtils.tla](https://github.com/tlaplus/tlaplus/issues/577#issuecomment-883781778) adds additional flexibility.

**Closed by lemmy** 2021-08-13 23:04 UTC
Labels: enhancement, help wanted, Tools

**Comment by aozgaa** [comment] 2023-03-01 05:59
This issue shows up in [section 2.3 of the PlusCal Tutorial](https://lamport.azurewebsites.net/tla/tutorial/session3.html#decl) if you try to follow along with command-line tools outside the toolbox (eg: vscode with [tlaplus extension](https://marketplace.visualstudio.com/items?itemName=alygin.vscode-tlaplus)).

(I'm seeing working outside the toolbox as a bit of a regrettable choice in hindsight)
