### ISSUE TITLE
Multi-threaded TLC Simulation Mode

### ISSUE THREAD

**Issue by will62794** [tlaplus/tlaplus#147] opened 2018-02-24 18:27 UTC
Currently, TLC does not take advantage of multiple threads when running in simulation mode (`-simulate`). It would be desirable to have this. Presumably, each thread would start up a simulation run with a different seed, to increase total randomized coverage. 

As a workaround, it is currently possible to start up multiple TLC processes (separate JVM instances) with different simulation seeds to achieve essentially the same effect.

**Comment by kapil-ms** [comment] 2018-04-12 14:56
+1

**Comment by will62794** [comment] 2018-07-24 11:45
@lemmy I started to explore this a bit. It would likely consist of refactoring [Simulator.java](https://github.com/tlaplus/tlaplus/blob/bfdbe00e3d0638b46a29ca408c91c0e17d832661/tlatools/src/tlc2/tool/Simulator.java) to start up multiple worker threads that each generate a random trace with different seeds. Eventually, I wonder if the trace simulator could be ported over to be an  implementation of the `AbstractChecker.java` interface. For example, as a `RandomizedModelChecker.java`, but that's a more significant change. Perhaps it could be a desirable code cleanup down the road, though. Are you on board with the `Simulator.java` recfactor approach? If so, I'll see if I can work on a patch in the next few weeks/month. 

On a somewhat unrelated note, I have been trying to figure out how to run a specific JUnit test from the command line. I am able to compile and run all tests with a command like 
```
ant -f tlatools/customBuild.xml compile compile-test dist test-dist
````
but haven't figured out how to run just a single test.

**Comment by will62794** [comment] 2018-09-14 03:47
@lemmy Another somewhat related question: is it possible to run the unit tests in parallel? It seems like you can set a `threads` parameter for [this](https://github.com/tlaplus/tlaplus/blob/master/tlatools/customBuild.xml#L334) JUnit task, but I'm wondering if it's supported given the way tests are currently written.

**Comment by lemmy** [comment] 2018-09-14 04:04
There is no support for running tests in parallel right now. The test suite however has become sufficiently large for parallelization to indeed be desirable. A potential problem is a directory name collision if two or more tests try to create TLC's temporary storage directory concurrently. util.FileUtil.makeMetaDir(Date, String, String) has support to append milliseconds to the directory name to minimize the collision probability though.

Fundamentally though, the problem is that each test has to run in its own JVM instance. This is owed to the fact that TLC does not correctly re-initializes some internal data-structures which makes checking of two or more different specs/models in a single JVM instance impossible.

Long-running tests won't gain much from parallelization as they run parallel TLC anyway (unless the test requires strict BFS).

**Comment by will62794** [comment] 2018-09-14 04:17
Yes, I suspected that the directory naming collisions might be an issue, but that could be worked around, as you said. 

The ant [docs](https://ant.apache.org/manual/Tasks/junit.html) seem to indicate that the `forkmode="perTest"` setting will create separate JVM instances for each test case. Does this not address the issue you stated about isolation between TLC instances? As far as performance gain, I was mainly thinking about small/medium sized test suites. For example, `test-dist` takes around 10 minutes on my local machine, and seems to run a bunch of relatively short tasks. Parallelizing that kind of task could be helpful. Being able to reduce that time by 2x, 4x, etc. with extra cores would be nice from a development perspective.

**Comment by lemmy** [comment] 2018-09-14 04:32
How does "perTest" work if two tests of a test case class use different specs/models?

**Comment by lemmy** [comment] 2018-10-05 04:57
@will62794 Today I was sufficiently annoyed by the slow tests myself and decided to give it a quick stab. 12h later I arrived at f9f35f35b74289d85b2f75b09f37703281f984de which halves the test suite's execution time from ~12min to ~6min on my machine.

**Comment by lemmy** [comment] 2018-11-01 01:04
Fixed by William with with 83559207381b08472f1d1dcf8bb07d08a7f9b089

**Comment by lemmy** [comment] 2018-11-02 03:02
When I run the spec in #204 with the multi-threaded simulation (even with ```-workers 1```), TLC spits out a duplicate trace.

```
TLC2 Version 2.13 of 18 July 2018
Running Random Simulation with seed -61556322235279500 with 1 worker on 4 cores with 5303MB heap and 64MB offheap memory (Linux 4.15.0-38-generic amd64, Oracle Corporation 1.8.0_191 x86_64).
Parsing file /home/markus/src/TLA/models/tlcbugs/Github204/Github204.toolbox/Model_1/MC.tla
Parsing file /home/markus/src/TLA/models/tlcbugs/Github204/Github204.toolbox/Model_1/Github204.tla
Parsing file /home/markus/src/TLA/tla/tlatools/class/tla2sany/StandardModules/TLC.tla
Parsing file /home/markus/src/TLA/tla/tlatools/class/tla2sany/StandardModules/Naturals.tla
Parsing file /home/markus/src/TLA/tla/tlatools/class/tla2sany/StandardModules/Sequences.tla
Parsing file /home/markus/src/TLA/tla/tlatools/class/tla2sany/StandardModules/FiniteSets.tla
Semantic processing of module Naturals
Semantic processing of module Github204
Semantic processing of module Sequences
Semantic processing of module FiniteSets
Semantic processing of module TLC
Semantic processing of module MC
Starting... (2018-11-01 19:59:27)
Implied-temporal checking--satisfiability problem has 1 branches.
Computed 1 initial states...
Error: Temporal properties were violated.

Error: The following behavior constitutes a counter-example:

State 1: <Initial predicate>
x = 5

State 2: <A line 8, col 6 to line 8, col 34 of module Github204>
x = 4

State 3: <A line 8, col 6 to line 8, col 34 of module Github204>
x = 3

State 4: <A line 8, col 6 to line 8, col 34 of module Github204>
x = 2

State 5: <A line 8, col 6 to line 8, col 34 of module Github204>
x = 1

State 6: <A line 8, col 6 to line 8, col 34 of module Github204>
x = 0

State 7: Stuttering
Error: Wrong invocation of TLC error printer. Error code not found.
Error: The behavior up to this point is:
State 1:
x = 5

State 2:
x = 4

State 3:
x = 3

State 4:
x = 2

State 5:
x = 1

State 6:
x = 0

State 7:
x = 0

The number of states generated: 7
Simulation using seed -61556322235279500 and aril 0
The number of states generated: 7
Simulation using seed -61556322235279500 and aril 0
Progress: 7 states checked.
Finished in 00s at (2018-11-01 19:59:27)
```

@will62794 Can you look into it?

**Comment by will62794** [comment] 2018-11-05 00:45
@lemmy I will look into fixing this.

**Comment by lemmy** [comment] 2018-11-15 05:04
There appears to still be a race condition when multiple workers run liveness checking and concurrently report a violation (tlc2.tool.liveness.LiveCheck1.printErrorTrace(BEGraphNode)).

**Comment by will62794** [comment] 2018-11-17 02:48
Hi @lemmy. I think this is just a synchronization issue with the liveness checker used by the SimulationWorkers. I can't claim to be very familiar with the internal details of liveness checking, but it appears that the `LiveCheck1.checkTrace` method isn't thread safe. I can easily reproduce the error you reference locally when running with just 2 workers:

```
java -cp dist/tla2tools.jar tlc2.TLC -workers 2 -deadlock -simulate -config test-model/simulation/BasicMultiTrace/MCLivenessProp.cfg BasicMultiTrace.tla
```

which produces a variety of different errors on different runs, all occurring inside `checkTrace`, e.g.

```
java.lang.NullPointerException
	at tlc2.tool.liveness.LiveCheck1.extractComponent(LiveCheck1.java:854)
	at tlc2.tool.liveness.LiveCheck1.checkComponent(LiveCheck1.java:812)
	at tlc2.tool.liveness.LiveCheck1.checkSccs(LiveCheck1.java:805)
	at tlc2.tool.liveness.LiveCheck1.checkSccs(LiveCheck1.java:795)
	at tlc2.tool.liveness.LiveCheck1.checkSccs(LiveCheck1.java:795)
	at tlc2.tool.liveness.LiveCheck1.checkSccs(LiveCheck1.java:795)
	at tlc2.tool.liveness.LiveCheck1.checkSccs(LiveCheck1.java:795)
	at tlc2.tool.liveness.LiveCheck1.checkSccs(LiveCheck1.java:795)
	at tlc2.tool.liveness.LiveCheck1.checkSccs(LiveCheck1.java:795)
	at tlc2.tool.liveness.LiveCheck1.checkTrace(LiveCheck1.java:504)
	at tlc2.tool.SimulationWorker.simulateRandomTrace(SimulationWorker.java:402)
	at tlc2.tool.SimulationWorker.run(SimulationWorker.java:225)
```

Adding `synchronized` to the `LiveCheck1.checkTrace` [method](https://github.com/tlaplus/tlaplus/blob/f09c6df8d41cae65c057fa2d552cbb4bb7ec1abf/tlatools/src/tlc2/tool/liveness/LiveCheck1.java#L483-L508) appears to trivially resolve the issue. I can run simulation mode repeatedly with 10 workers, for example, and no errors occur when checking a liveness violation. I tried this out mainly to verify my hunch.

I figured I would ask for your advice on resolving this issue. If the `checkTrace` method is only called in simulation mode, then I suppose it would be feasible to synchronize access to it, but it may ruin scalability of parallel simulation mode. Alternatively, we could just give each SimulationWorker its own dedicated liveness checker. What do you think?

Note: I'm not exactly sure how liveness checks during exhaustive BFS model checking works, but it appears that those workers use the `addNextState` and `finalCheck` methods of the `ILiveCheck` interface, which presumably _are_ thread safe? As far as I could tell, `finalCheck` is only called at the end of model checking, from a single thread, so there would be no issue for that method.

**Comment by lemmy** [comment] 2018-11-17 05:34
For now lets just synchronize LiveCheck1#checkTrace. Later simulation can be changed to use one LiveCheck1 instances per SimulationWorker. Do you want to open a pull request?

**Comment by lemmy** [comment] 2018-11-17 06:44
605fb0f9c0a77ce3572955eda94c5ed1909531ce

Just for LiveCheck1 because (I believe) LiveCheck is thread-safe.

**Closed** 2019-05-15 18:05 UTC
Labels: Tools, enhancement, help wanted
