### ISSUE TITLE
Trace minimization when using simulation

### ISSUE THREAD

**Issue by Vanlightly** [tlaplus/tlaplus#1049] opened 2024-10-22 14:29 UTC
It would be very useful if TLC could perform minimization after encountering an invariant violation, when using simulation. I often use simulation as I can explore larger state spaces, but counterexamples can be overly noisy and long with a large number of irrelevant steps.

Is it possible to implement minimization, similar to how property based test frameworks do?

**Comment by lemmy** [comment] 2024-10-22 15:06
Closing this issue as it seems to be a duplicate of the one found at https://github.com/tlaplus/tlaplus/issues/400.  Can you please explain add a comment in #400 explaining how PBT minimizes counterexamples?

**Closed by lemmy** 2024-10-22 15:06 UTC
