### ISSUE TITLE
Nondeterminism in diameter reported by TLC

### ISSUE THREAD

**Issue by ahelwer** [tlaplus/tlaplus#883] opened 2024-02-21 21:58 UTC
## Description
TLC occasionally reports varying diameter values with multiple workers. As discovered in this PR: https://github.com/tlaplus/Examples/pull/122

## Expected Behavior
Diameter is expected to be deterministic, per Markus.

## Actual Behavior
TLC will occasionally report varying state graph diameter, although the total & distinct states remain the same.

## Steps to Reproduce
1. Check out the tlaplus/examples repo
2. Download a recent version of tla2tools.jar
4. Repeatedly run the model for `specifications/glowingRaccoon/clean.tla` or `specifications/Paxos/MCVoting.cfg` with -workers greater than 1
5. Observe that the reported diameter varies

## Steps Taken to Fix
N/A

## Possible Fix
N/A

## Your Environment
Has been reproduced across multiple OSs and (recent) versions of TLC.

**Comment by FedericoPonzi** [comment] 2024-06-11 17:18
Yes I'm currently looking into this one. You can also assign it to me, thanks

**Comment by lemmy** [comment] 2024-06-11 17:39
Assigned (looks like you had to comment in order for the Github UI to let me do that).

**Comment by FedericoPonzi** [comment] 2024-06-11 20:45
Issue: When running the model with multiple workers, sometime the maxLevel (or max Depth) is larger then usual.
Some findings first:
1. the states are generated correctly. The same number of states is generated. The state graph is the same (I suspect).
2. It doesn't reproduce with _all_ specifications.
3. I've tried to go as back as 2018 and the bug was already there.

The ModelChecker involved is running a BFS. I wanted to try the DFS one, but apparently it just doesn't work yet with multiple workers (https://github.com/tlaplus/tlaplus/issues/548 seems like a good issue to look into). 

Anyways, what's happening is that when a worker is faster then another, a node is discovered from a longer path. 
Suppose we have this tree:
![Untitled Diagram drawio](https://github.com/tlaplus/tlaplus/assets/2124904/ae302dc0-1ecd-430c-a753-6e6e88115fd0)

A sequential BFS would visit the tree in the following order:
1. visit A
2. visit B
4. visit C
5. visit E
6. visit D

E and D are effectively at depth 2. A concurrent visit with two threads (the prefix is the thread id):
1. 0: Visit A
2. 0: Take B, go to sleep
3. 2: Visit C
4. 2: Visit D
5. 2: Visit E
7. 0: Visit B

Now node E is at depth 3 and boom. For the specification in exam, I first reduced the constants of `DNA` and `PRIMER` to `4` (to reduce the state graph size), then I've generated the dot of the state graph:
```
java  -cp ./dist/tla2tools.jar tlc2.TLC  -dump dot test.dot /home/fponzi/dev/tla+/Examples/specifications/glowingRaccoon/clean.tla
```
![image](https://github.com/tlaplus/tlaplus/assets/2124904/38c709b8-b892-46d0-b9fd-85593f0467ca)

Then in the codebase, I've patched the code [here](https://github.com/tlaplus/tlaplus/blob/3c119e1504e146f8dbe8637cf4d548e5f5e4630a/tlatools/org.lamport.tlatools/src/tlc2/tool/Worker.java#L440) with:

```
if(succState.getLevel() > 10){
    this.tlc.trace.printTrace(curState, succState);
}
```
To get the attached stack trace: [stacktrace.txt](https://github.com/user-attachments/files/15794561/stacktrace.txt)

If you follow the stack trace from the graph above, you will find that it's a fair execution. This is possible because the next states are generated from the previous states from within the worker itself. It there was a single place generating the nodes to visit this would have been avoided. This doesn't help but I also haven't thought of a solution yet, but wanted to share my findings.

**Comment by ahelwer** [comment] 2024-06-11 20:54
Is this deterministic depth feature even implemented for multiple workers then? The algorithm should be to ensure all states with depth <= N-1 (where N is the depth of the error state) are visited before terminating, right? I can't imagine what it would be otherwise.

**Comment by lemmy** [comment] 2024-06-11 21:58
> Is this deterministic depth feature even implemented for multiple workers then? The algorithm should be to ensure all states with depth < N (where N is the depth of the error state) are visited before terminating, right? I can't imagine what it would be otherwise.

@FedericoPonzi Thanks for the refresher! No, a deterministic diameter is not what TLC implements, as that would require additional synchronization, limiting scalability. For small models, use a single worker. For large models, the diameter will almost always appear deterministic.

**Comment by FedericoPonzi** [comment] 2024-06-11 22:34
Unless @ahelwer wants to do it, I can try to find a good place to persist this information.

**Comment by ahelwer** [comment] 2024-06-11 22:36
All yours!

**Comment by lemmy** [comment] 2024-06-11 22:49
There are the [Toolbox help](https://github.com/tlaplus/tlaplus/tree/master/toolbox/org.lamport.tla.toolbox.doc/html), the [command-line help](https://github.com/tlaplus/tlaplus/blob/10033c2fd3528ec9d6a20f552f4e1f4a2dba1394/tlatools/org.lamport.tlatools/src/tlc2/TLC.java#L1523-L1695), and [current tools](https://lamport.azurewebsites.net/tla/current-tools.pdf) ([markdown](https://github.com/tlaplus/tlaplus/blob/master/general/docs/current-tools.md) clone).  The PDF is under Leslie's control.

**Comment by lemmy** [comment] 2024-06-12 15:05
For larger, real-world specifications and models, a non-deterministic diameter is generally not an issue, except in pathological cases.

The state queue remains the primary bottleneck in TLC's breadth-first search. To improve scalability, efforts to replace the the state queue should focus on that.  Replacing it is not a trivial task because TLC workers globally synchronize on the state queue during checkpoints or liveness checking.  A few years ago, I began [designing](https://github.com/lemmy/pagequeue) a more scalable state queue based on dynamically sized sets of unexplored states.

**Comment by lemmy** [comment] 2024-06-12 15:27
More background:

If I recall correctly, @Calvin-L once created a prototype for a priority queue. However, I am unsure whether this prototype replaced StateQueue.java or was derived from it.  My recent work on StateDeque.java does derive from StateQueue.java, as I did not have the time to refactor the global synchronization out of StateQueue.java.  [StateQueue.java Verification](https://github.com/tlaplus/tlaplus/tree/master/tlatools/org.lamport.tlatools/test-verify/tlc2/tool/queue) verifies deadlock-freedom of StateQueue.java.  Note that our performance and scalability benchmarks are currently offline because we no longer have access to suitable hardware. These benchmarks are essential for any performance or scalability-related work on TLC.

**Comment by ahelwer** [comment] 2024-06-12 17:11
That sounds like an interesting concurrency problem! I also wonder what it would take to get a decent benchmarking system in place again. I don't know much about scientifically-valid benchmarking techniques honestly.

**Comment by lemmy** [comment] 2024-06-12 17:26
We have a decent benchmarking system that can be easily extended with additional workloads, i.e., spec/models.  However, the system currently lacks dedicated hardware since our previous sponsor withdrew.  Perhaps, it is possible to request resources from the TLA+ Foundation.

**Comment by lemmy** [comment] 2024-06-21 17:20
Done

**Closed by lemmy** 2024-06-21 17:20 UTC
Labels: enhancement, help wanted, Tools
