### ISSUE TITLE
Bundle the JVM in the Toolbox

### ISSUE THREAD

**Issue by pron** [tlaplus/tlaplus#176] opened 2018-07-27 18:05 UTC
The current recommended practice for desktop Java applications is to bundle the JVM with the application.

**Comment by lemmy** [comment] 2018-10-02 14:28
@diegoholiveira Which version of Java is this exactly?

**Comment by diegoholiveira** [comment] 2018-10-02 15:02
```
$ java -version
java version "11" 2018-09-25
Java(TM) SE Runtime Environment 18.9 (build 11+28)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11+28, mixed mode)
```

**Comment by lemmy** [comment] 2018-10-03 16:10
Anyone already figured out which one of the various JDK flavors (Oracle, Azul, OpenJDK, ...) would be the right fit to bundle license-wise?

**Comment by caizixian** [comment] 2018-10-09 03:12
I'm having this problem as well.
I have JDK 8 and 11 installed on my macOS. Even though I set my `JAVA_HOME` to JDK 8, `./toolbox` still doesn't launch.
Is there any workaround so that I can have multiple JDK side-by-side?

**Comment by lemmy** [comment] 2018-10-11 04:40
https://wiki.eclipse.org/Eclipse.ini#-vm_value:_Mac_OS_X_Example explains how to wire a specific JRE installation to the Toolbox. Just replace "eclipse" with "toolbox" in the instructions.

**Comment by caizixian** [comment] 2018-10-11 05:57
@lemmy
`./toolbox -vm /usr/bin` doesn't work even though
```
/usr/bin/java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
```

However, explicitly specifying JDK works. 

Thanks for the suggestion

**Comment by louy2** [comment] 2018-12-05 10:16
The community consensus seems to be that OpenJDK is the default choice going forward from Java 11 in open source projects. That said, from this [Reddit post](https://www.reddit.com/r/java/comments/8jvv8e/what_would_be_the_reasons_to_use_the_zulu_build/) by an Azul employee, there shouldn't be any differences between using Zulu and OpenJDK, and license should not be a problem due to exception clauses added to the GPLv2 OpenJDK is using.

The reason Zulu doesn't seem to have JFR is because [JFR used to be proprietary](https://dzone.com/articles/using-java-flight-recorder-with-openjdk-11-1). It is only with Java 11 that it is open sourced and free to use in production. I am not sure this applies to previous versions, so maybe bundling JRE requires adopting Java 11. Btw, what's the latest JRE the toolbox supports?

**Comment by lemmy** [comment] 2018-12-05 16:14
@louy2 Did you try the released 1.5.7 Toolbox or the [current nightly](https://tla.msr-inria.inria.fr/tlatoolbox/ci/products/) where I recently fixed a Java11 [incompatibility](https://github.com/tlaplus/tlaplus/commit/96b4ea1c0bf60d930c856204da42f2b21f6858c3)?

**Comment by louy2** [comment] 2018-12-18 03:03
@noahdesu 
That error message is exactly the one fixed in the patch linked by @lemmy 

Now that Java 11 support is out of the way, there seems to be no technical obstacle before bundling JVM. But it also takes away the urgency to bundling JVM ¯\_(ツ)_/¯

**Comment by waltertross** [comment] 2018-12-23 23:06
The nightly in https://tla.msr-inria.inria.fr/tlatoolbox/ci/products/ , which unfortunately goes by exactly the same filename (`TLAToolbox-1.5.7-macosx.cocoa.x86_64.zip`), also fixed my problem, which was

`[wtross /Applications/TLA+ Toolbox.app/Contents/MacOS]$ java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
`

`[wtross /Applications/TLA+ Toolbox.app/Contents/MacOS]$ ./toolbox 
Error occurred during initialization of boot layer
java.lang.module.FindException: Module java.se.ee not found
`
Just repeating for clarity

**Comment by lemmy** [comment] 2018-12-24 23:44
@waltertross 1.5.7 will be incremented to 1.5.8 during the actual release preparation.  The timestamp suffix of the various ```feature/org.lamport.tla.toolbox.feature.*_1.0.0.201812102241``` allows to distinguish a nightly build from the 1.5.7 release.

**Comment by lemmy** [comment] 2019-01-16 05:35
https://github.com/tlaplus/tlaplus/blob/master/general/docs/java-toolbox-installation.md

**Comment by lemmy** [comment] 2019-01-21 20:11
JEP 343: https://jdk.java.net/jpackage/

**Comment by lemmy** [comment] 2019-01-27 23:14
https://twitter.com/lemmster/status/1089656514892070912

**Comment by lemmy** [comment] 2019-01-27 23:14
Issue #120 related

**Comment by quaeler** [comment] 2019-01-31 17:59
Rounding the corner...
![screen shot 2019-01-31 at 9 48 52 am](https://user-images.githubusercontent.com/22581048/52074508-e57ec000-253e-11e9-9dd7-6da79f6028d8.png)

**Comment by hatch-carl** [comment] 2019-03-05 15:14
MacOS user here with issues. I had to dig a lot to get the toolbox working. For future adventurers, here is what you must do:

1. Download the TLA+ Toolbox release [as advised](http://lamport.azurewebsites.net/tla/toolbox.html).
2. Download the [AdoptOpenJDK](https://adoptopenjdk.net) JRE 8 Hotspot release and install it with the package installer.
3. Discover the full java home path for the AdoptOpenJDK 8 by running `/usr/libexec/java_home --verbose` and looking at the last field in the line containing that JDK's name. `/Library/Java/JavaVirtualMachines/adopt...`. Copy that whole line.
4. Find the path to the TLA+ Toolbox, likely something like: `/Applications/TLA+ Toolbox.app`.
5. Write a small shell script called `tlaplus` to act as a shortcut for launching the app and put it where you can easily execute it from the terminal. You will need to invoke the toolbox binary in the application package directly and specify an option flag `vm` to the program with the full JDK path plus `/bin/java`. Be sure to `chmod +x tlaplus`

Example shell script.
```bash
#! /bin/bash

/Applications/TLA+\ Toolbox.app/Contents/MacOS/toolbox -vm /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java
```

Run from the shell script.

P.S.
I could not successfully apply the instructions to install eclipse in Macos and set the JRE. The `toolbox.ini` file does not seem to be picked up before the program exits with an error. It does not matter whether I execute it by clicking the application or run the `toolbox` binary from inside the application package.

**Comment by lemmy** [comment] 2019-03-14 03:45
Thanks to @quaeler the [Toolbox nightly builds](http://nightly.tlapl.us) bundle a Java11 VM now.

**Closed by lemmy** 2019-03-14 03:45 UTC
Labels: Toolbox, Tools, enhancement

**Comment by gsalierno** [comment] 2019-03-25 10:14
I'm not able to execute the bundle provided by @quaeler. When I run the toolbox the following error prompt: 

`The JVM shared library "/Users/user/Desktop/TLA+ Toolbox.app/Contents/Eclipse/plugins/org.lamport.openjdk.macosx.x86_64_11.0.2.9/Contents/Home/bin/../lib/server/libjvm.dylib"
does not contain the JNI_CreateJavaVM symbol.`

`java 11.0.2 2019-01-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+9-LTS, mixed mode)`

**Comment by quaeler** [comment] 2019-03-25 15:06
It's not clear from where you are getting the bundle. If you are building the Toolbox locally, we made some fixes to the macOS version of the bundle early last week, but unfortunately failed to increment the version deployed - so you would need to delete your local cache:
```
	rm -rf ~/.m2/repository/p2/org/eclipse/update/feature/org.lamport.openjdk.feature
	rm -rf ~/.m2/repository/p2/osgi/bundle/org.lamport.openjdk.*
```
and then rebuild.
If you're using ~nightly builds, you'll need to pick one up from the last few days.
If there is a door 3, please let me know.

**Comment by lemmy** [comment] 2019-03-25 15:33
Last week's changes seem to have caused a regression (with today's nightly build):

<img width="435" alt="image001" src="https://user-images.githubusercontent.com/88777/54932774-a9316580-4ed8-11e9-818f-ad2833dbda7d.png">

**Comment by gsalierno** [comment] 2019-03-25 15:36
> Last week's changes seem to have caused a regression (with today's nightly build):
> 
> <img alt="image001" width="435" src="https://user-images.githubusercontent.com/88777/54932774-a9316580-4ed8-11e9-818f-ad2833dbda7d.png">

This is exactly what I've experienced with the last nightly build available at [Toolbox nightly builds](http://nightly.tlapl.us/products/)

**Comment by quaeler** [comment] 2019-03-25 15:51
Perhaps the nightly build system did not get it's cache clean out either... @lemmy ?

**Comment by quaeler** [comment] 2019-03-25 15:58
If i nuke my local cache once again and build against the master-sync i did on the 23rd, i have a functioning Toolbox & TLC agent.

**Comment by lemmy** [comment] 2019-03-25 16:01
.repository/ has been purged and a [new build requested](https://tla.msr-inria.inria.fr/build/job/M-HEAD-master-Toolbox.product.standalone/605/).  Build results will be available within the next hour.

**Comment by lemmy** [comment] 2019-03-25 18:00
New [nightly build](http://nightly.tlapl.us/) from purged repository fixes issue for me.

**Comment by gsalierno** [comment] 2019-03-26 08:13
I confirm the last build fixed the problem also for me
