### ISSUE TITLE
Does not start on OSX:  "An error has occured"

### ISSUE THREAD

**Issue by jbulow** [tlaplus/tlaplus#61] opened 2017-07-02 19:23 UTC
The log file refered to in the message:

!SESSION 2017-07-02 21:21:48.905 -----------------------------------------------
eclipse.buildId=1.5.3
java.version=1.8.0_92
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -keyring /Users/jonas/.eclipse_keyring -showlocation
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -keyring /Users/jonas/.eclipse_keyring -showlocation

!ENTRY org.lamport.tla.toolbox.product.standalone 1 -1 2017-07-02 21:21:51.473
!MESSAGE TLA+ Toolbox started with 1 arguments.

!ENTRY org.lamport.tla.toolbox.product.standalone 1 -1 2017-07-02 21:21:51.473
!MESSAGE -showlocation

!ENTRY org.eclipse.osgi 4 0 2017-07-02 21:21:51.480
!MESSAGE Application error
!STACK 1
java.lang.IllegalStateException: The platform metadata area could not be written: /private/var/folders/wp/_c3dfz2x1wz70v2y657qrvd80000gs/T/AppTranslocation/CC9C8987-09C8-43B2-8D6C-B11995EB7A2B/d/TLA+ Toolbox.app/Contents/MacOS/workspace/.metadata.  By default the platform writes its content
under the current working directory when the platform is launched.  Use the -data parameter to
specify a different content area for the platform.
        at org.eclipse.core.internal.runtime.DataArea.assertLocationInitialized(DataArea.java:61)
        at org.eclipse.core.internal.runtime.DataArea.getStateLocation(DataArea.java:124)
        at org.eclipse.core.internal.runtime.InternalPlatform.getStateLocation(InternalPlatform.java:539)
        at org.eclipse.core.runtime.Plugin.getStateLocation(Plugin.java:319)
        at org.lamport.tla.toolbox.Application.start(Application.java:51)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1515)

!ENTRY org.lamport.tla.toolbox.product.standalone 4 0 2017-07-02 21:21:51.537
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Exception in org.lamport.tla.toolbox.StandaloneActivator.stop() of bundle org.lamport.tla.toolbox.product.standalone.
        at org.eclipse.osgi.internal.framework.BundleContextImpl.stop(BundleContextImpl.java:847)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.stopWorker0(EquinoxBundle.java:955)
        at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.stopWorker(EquinoxBundle.java:323)
        at org.eclipse.osgi.container.Module.doStop(Module.java:626)
        at org.eclipse.osgi.container.Module.stop(Module.java:488)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.decStartLevel(ModuleContainer.java:1623)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1542)
        at org.eclipse.osgi.container.SystemModule.stopWorker(SystemModule.java:248)
        at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule.stopWorker(EquinoxBundle.java:144)
        at org.eclipse.osgi.container.Module.doStop(Module.java:626)
        at org.eclipse.osgi.container.Module.stop(Module.java:488)
        at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:186)
        at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:159)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: The platform metadata area could not be written: /private/var/folders/wp/_c3dfz2x1wz70v2y657qrvd80000gs/T/AppTranslocation/CC9C8987-09C8-43B2-8D6C-B11995EB7A2B/d/TLA+ Toolbox.app/Contents/MacOS/workspace/.metadata.  By default the platform writes its content
under the current working directory when the platform is launched.  Use the -data parameter to
specify a different content area for the platform.
        at org.eclipse.core.internal.runtime.DataArea.assertLocationInitialized(DataArea.java:61)
        at org.eclipse.core.internal.runtime.DataArea.getStateLocation(DataArea.java:129)
        at org.eclipse.core.internal.preferences.InstancePreferences.getBaseLocation(InstancePreferences.java:44)
        at org.eclipse.core.internal.preferences.InstancePreferences.initializeChildren(InstancePreferences.java:199)
        at org.eclipse.core.internal.preferences.InstancePreferences.<init>(InstancePreferences.java:59)
        at org.eclipse.core.internal.preferences.InstancePreferences.internalCreate(InstancePreferences.java:209)
        at org.eclipse.core.internal.preferences.EclipsePreferences.create(EclipsePreferences.java:391)
        at org.eclipse.core.internal.preferences.EclipsePreferences.create(EclipsePreferences.java:379)
        at org.eclipse.core.internal.preferences.PreferencesService.createNode(PreferencesService.java:389)
        at org.eclipse.core.internal.preferences.RootPreferences.getChild(RootPreferences.java:63)
        at org.eclipse.core.internal.preferences.RootPreferences.getNode(RootPreferences.java:101)
        at org.eclipse.core.internal.preferences.RootPreferences.node(RootPreferences.java:90)
        at org.eclipse.core.internal.preferences.legacy.PreferenceForwarder.<init>(PreferenceForwarder.java:37)
        at org.eclipse.core.runtime.Plugin$1.run(Plugin.java:378)
        at org.eclipse.core.runtime.Plugin.getPluginPreferences(Plugin.java:381)
        at org.eclipse.core.runtime.Plugin.savePluginPreferences(Plugin.java:409)
        at org.eclipse.ui.plugin.AbstractUIPlugin.savePreferenceStore(AbstractUIPlugin.java:536)
        at org.eclipse.ui.plugin.AbstractUIPlugin.stop(AbstractUIPlugin.java:647)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$4.run(BundleContextImpl.java:827)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$4.run(BundleContextImpl.java:1)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.stop(BundleContextImpl.java:820)
        ... 13 more
Root exception:
java.lang.IllegalStateException: The platform metadata area could not be written: /private/var/folders/wp/_c3dfz2x1wz70v2y657qrvd80000gs/T/AppTranslocation/CC9C8987-09C8-43B2-8D6C-B11995EB7A2B/d/TLA+ Toolbox.app/Contents/MacOS/workspace/.metadata.  By default the platform writes its content
under the current working directory when the platform is launched.  Use the -data parameter to
specify a different content area for the platform.
        at org.eclipse.core.internal.runtime.DataArea.assertLocationInitialized(DataArea.java:61)
        at org.eclipse.core.internal.runtime.DataArea.getStateLocation(DataArea.java:129)
        at org.eclipse.core.internal.preferences.InstancePreferences.getBaseLocation(InstancePreferences.java:44)
        at org.eclipse.core.internal.preferences.InstancePreferences.initializeChildren(InstancePreferences.java:199)
        at org.eclipse.core.internal.preferences.InstancePreferences.<init>(InstancePreferences.java:59)
        at org.eclipse.core.internal.preferences.InstancePreferences.internalCreate(InstancePreferences.java:209)
        at org.eclipse.core.internal.preferences.EclipsePreferences.create(EclipsePreferences.java:391)
        at org.eclipse.core.internal.preferences.EclipsePreferences.create(EclipsePreferences.java:379)
        at org.eclipse.core.internal.preferences.PreferencesService.createNode(PreferencesService.java:389)
        at org.eclipse.core.internal.preferences.RootPreferences.getChild(RootPreferences.java:63)
        at org.eclipse.core.internal.preferences.RootPreferences.getNode(RootPreferences.java:101)
        at org.eclipse.core.internal.preferences.RootPreferences.node(RootPreferences.java:90)
        at org.eclipse.core.internal.preferences.legacy.PreferenceForwarder.<init>(PreferenceForwarder.java:37)
        at org.eclipse.core.runtime.Plugin$1.run(Plugin.java:378)
        at org.eclipse.core.runtime.Plugin.getPluginPreferences(Plugin.java:381)
        at org.eclipse.core.runtime.Plugin.savePluginPreferences(Plugin.java:409)
        at org.eclipse.ui.plugin.AbstractUIPlugin.savePreferenceStore(AbstractUIPlugin.java:536)
        at org.eclipse.ui.plugin.AbstractUIPlugin.stop(AbstractUIPlugin.java:647)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$4.run(BundleContextImpl.java:827)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$4.run(BundleContextImpl.java:1)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.stop(BundleContextImpl.java:820)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.stopWorker0(EquinoxBundle.java:955)
        at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.stopWorker(EquinoxBundle.java:323)
        at org.eclipse.osgi.container.Module.doStop(Module.java:626)
        at org.eclipse.osgi.container.Module.stop(Module.java:488)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.decStartLevel(ModuleContainer.java:1623)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1542)
        at org.eclipse.osgi.container.SystemModule.stopWorker(SystemModule.java:248)
        at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule.stopWorker(EquinoxBundle.java:144)
        at org.eclipse.osgi.container.Module.doStop(Module.java:626)
        at org.eclipse.osgi.container.Module.stop(Module.java:488)
        at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:186)
        at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:159)
        at java.lang.Thread.run(Thread.java:745)

!ENTRY org.eclipse.ui 4 0 2017-07-02 21:21:51.538
!MESSAGE FrameworkEvent ERROR
!STACK 0
java.lang.IllegalStateException: BundleContext is no longer valid
        at org.eclipse.osgi.internal.framework.BundleContextImpl.checkValid(BundleContextImpl.java:983)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.removeBundleListener(BundleContextImpl.java:334)
        at org.eclipse.ui.plugin.AbstractUIPlugin$2.bundleChanged(AbstractUIPlugin.java:620)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:902)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

**Comment by lemmy** [comment] 2017-07-02 19:30
Hi, is this a duplicate of https://github.com/tlaplus/tlaplus/issues/56?

**Comment by jbulow** [comment] 2017-07-02 19:58
Yes, it seems to be similar. It worked if I moved the application from the Downdload folder to the Applications folder.

**Closed** 2017-07-07 08:34 UTC
Labels: question, Toolbox
