### ISSUE TITLE
"Open root file" window does not show the "File name" text box and "Open" button (Manjaro Linux XFCE)

### ISSUE THREAD

**Issue by rodrigocarlson** [tlaplus/tlaplus#166] opened 2018-05-30 00:31 UTC
- Manjaro Linux 17.1.10
- XFCE 4.12
- Kernel 4.14.44-1-MANJARO
- Java
openjdk version "1.8.0_172"
OpenJDK Runtime Environment (build 1.8.0_172-b11)
OpenJDK 64-Bit Server VM (build 25.172-b11, mixed mode)

Attempt creating a new spec:
File -> Open Spec -> Add New Spec... -> Browse

The "Open root file" window that appears after clicking "Browse" does not show the "File name" text box and "Open" button. See the attached image and compare it with the Windows behavior (TLA+ Video Course  3 around 3:24).

This problem forces the user to type the Root-module path and file name by hand (or selecting and existing tla file previously created by hand).

![screenshot_2018-05-29_21-19-24](https://user-images.githubusercontent.com/34322511/40692085-11cf85d4-6386-11e8-8900-100f907efe0b.png)

**Comment by lemmy** [comment] 2018-05-30 05:58
Duplicate of #135

**Closed by lemmy** 2018-05-30 05:58 UTC
