### ISSUE TITLE
why assert failed don't show the Error-Trace?

### ISSUE THREAD

**Issue by magicsupery** [tlaplus/tlaplus#541] opened 2020-11-26 08:25 UTC
when the assert failed, i only got the error the assert line, but when in a complex system, it`s hard to figure out the reason.
so why toolbox do not show the error-trace?

**Comment by lemmy** [comment] 2020-11-26 16:43
Duplicate of https://github.com/tlaplus/tlaplus/commit/19757bdd6aadf7c0e371c40bf591f0d84f12a592

Please use a recent [nightly build](https://nightly.tlapl.us).

**Closed by lemmy** 2020-11-26 16:43 UTC
