### ISSUE TITLE
Java 21 causes TLC's BufferedRandomAccessFileTest and OffHeapDiskFPSetTest to fail

### ISSUE THREAD

**Issue by lemmy** [tlaplus/tlaplus#835] opened 2023-10-23 20:00 UTC
Some methods such as `tlc2.util.BufferedRandomAccessFile#readLong` that used to throw `IOException` have started to throw `ArrayIndexOutOfBoundsExceptions`.

**Comment by Calvin-L** [comment] 2023-12-07 20:32
I'm looking at putting together a fix for this.

I'm very impressed with the quality and clarity of `BufferedRandomAccessFile`, but it seems to contain a critical incorrect assumption:
https://github.com/tlaplus/tlaplus/blob/7fcaceb9c17abd2c2b65903ad7a76b6cf17e5cca/tlatools/org.lamport.tlatools/src/tlc2/util/BufferedRandomAccessFile.java#L55

But, in reality, ["The offset may be set beyond the end of the file"](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/io/RandomAccessFile.html#seek(long)).

In JDK<21, [`readLong()`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/io/RandomAccessFile.html#readLong()) and friends were implemented using repeated calls to `read()`. In JDK>=21 they are implemented using a bulk array read. That change in behavior seems to have revealed the incorrect assumption above. When seeking past the end of the file, some of the checks and math in `BufferedRandomAccessFile` don't work as intended. It ends up breaking its own internal invariants (in particular, it enters a state where `this.curr > this.hi`).

I think fixing this issue will require relaxing the invariant that `lo <= curr <= hi`:
https://github.com/tlaplus/tlaplus/blob/master/tlatools/org.lamport.tlatools/src/tlc2/util/BufferedRandomAccessFile.java#L72

**Comment by Calvin-L** [comment] 2024-01-02 22:26
@lemmy I discovered something else interesting while testing my changes. The tests include:
```java
	@Test
	public void testReadSeek() throws IOException {
		final File tmpFile = File.createTempFile("BufferedRandomAccessFileTest_testReadSeek", ".bin");
		tmpFile.deleteOnExit();
		final java.io.RandomAccessFile raf = new BufferedRandomAccessFile(tmpFile, "rw");
		
		raf.setLength(BufferedRandomAccessFile.BuffSz + 1L);
		raf.seek(1);
		
		for (int i = 0; i < BufferedRandomAccessFile.BuffSz / 8; i++) {
			assertEquals(0L, raf.readLong());
		}
		raf.close();
	}
```

That test checks that `setLength` fills the new content with zeros when it extends the file. But [that isn't promised by the underlying RandomAccessFile](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/io/RandomAccessFile.html#setLength(long)):
 > If the present length of the file as returned by the length method is smaller than the newLength argument then the file will be extended. In this case, the contents of the extended portion of the file are not defined.

Do you know if any clients of `BufferedRandomAccessFile` actually require the fill-with-zeros behavior? We could certainly add that as a guarantee. But, since it isn't promised by `RandomAccessFile.setLength`, we might incur some performance penalty doing it ourselves.

**Comment by lemmy** [comment] 2024-01-03 18:14
I've reviewed the different fingerprint sets to refresh my memory. I recall that the `OffHeapDiskFPSet` needs its in-memory representation to be zeroed. However, when using disk files, there's no need to zero the files. If I remember correctly, the FPSets always write data up to the full length of the file.  I also don't recall any clients in the liveness package to require zeroed files.

**Closed** 2024-06-12 18:06 UTC
Labels: bug, Tools
