### ISSUE TITLE
Mac: TLA+ crashes when displaying pdf

### ISSUE THREAD

**Issue by CThuleHansen** [tlaplus/tlaplus#435] opened 2020-03-05 15:05 UTC
1. Visualize state graph after completion of model checking causes TLA+ toolbox to crash.
It does generate the pdf and dot, and I can open it fine manually.
2. Furthermore, it crashes on subsequent access to the given model.

Specs:
Mac Catalina 10.15.3
dot - graphviz version 2.42.3 (20191010.1750)
pdfTeX 3.14159265-2.6-1.40.20 (TeX Live 2019)

I cannot set the default pdf app in TLA+ preferences, but my system default is mac preview. 
1. Crash log upon visualising state graph: 
```
Process:               toolbox [46779]
Path:                  /Applications/TLA+ Toolbox.app/Contents/MacOS/toolbox
Identifier:            org.lamport.tla.toolbox.product.product
Version:               1.6.0 (1.6.0.201907102009)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           toolbox [46779]
User ID:               704577350

Date/Time:             2020-03-05 16:01:03.498 +0100
OS Version:            Mac OS X 10.15.3 (19D76)
Report Version:        12
Bridge OS Version:     4.2 (17P3050)
Anonymous UUID:        D504EC15-C740-4612-A9C7-EB29BB256923

Sleep/Wake UUID:       5FCC6028-1DCE-4BBD-99EC-5232DA851A8A

Time Awake Since Boot: 150000 seconds
Time Since Wake:       26000 seconds

System Integrity Protection: enabled

Crashed Thread:        65

Exception Type:        EXC_BAD_ACCESS (SIGABRT)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00000000000000c0
Exception Note:        EXC_CORPSE_NOTIFY

VM Regions Near 0xc0:
--> 
    __TEXT                 00000001068c9000-00000001068cd000 [   16K] r-x/rwx SM=COW  /Applications/TLA+ Toolbox.app/Contents/MacOS/toolbox

Application Specific Information:
abort() called
```

**Comment by lemmy** [comment] 2020-03-05 16:15
This sound like a duplicate of https://github.com/tlaplus/tlaplus/issues/357

**Comment by quaeler** [comment] 2020-03-06 03:24
If you move to a nightly build, version 1.6.1 features an option to have the PDFs be opened by your OS (and so the Toolbox would launch Preview.app with the PDF.)

**Comment by CThuleHansen** [comment] 2020-03-06 08:00
> This sounds like a duplicate of #357

Could be, although it is not the spec that is pretty printed and the pdf editor is different. 

> If you move to a nightly build, version 1.6.1 features an option to have the PDFs be opened by your OS (and so the Toolbox would launch Preview.app with the PDF.)

I will try this.

**Comment by lemmy** [comment] 2020-03-10 16:16
https://nightly.tlapl.us/products/

**Comment by lemmy** [comment] 2020-04-18 04:15
Closing because no longer reproducible.  Please reopen if this remains an issue with https://nightly.tlapl.us/products/

**Closed by lemmy** 2020-04-18 04:15 UTC
Labels: Toolbox, bug
