### ISSUE TITLE
"TLC Model Checker" > "Run Model" menu item enabled even without a model

### ISSUE THREAD

**Issue by davidp3** [tlaplus/tlaplus#189] opened 2018-09-09 16:40 UTC
I installed the Toolbox a few days ago but I haven't been able to get it to do anything with any specs.  

Steps to Reproduce:
* Download and unzip TLAToolbox-1.5.7-win32.win32.x86_64.zip
* Run Toolbox.exe from Windows Explorer
* Open a spec -- for example:  Examples/specifications/allocator/SimpleAllocator.tla
* Select "Run Model" from the menu

Expected Results:
Something happens

Actual Results:
Nothing happens

------

I'm not sure what the console is for but it doesn't show any output either when exposed.  It just says "No consoles to display at this time".  Note that parsing specs works fine and that I have tried this with a number of specs that parse and have theorems.

**Comment by lemmy** [comment] 2018-09-09 17:54
@davidp3 Did you create a model (TLC Model Checker > New Model...) before clicking "Run Model"?

**Comment by davidp3** [comment] 2018-09-09 19:11
Thanks, that's what I was missing.  I'd been trying to do the examples in the early chapters of book but it didn't see a mention of this.

**Comment by lemmy** [comment] 2019-03-14 21:27
@quaeler thanks, pushed.

**Comment by lemmy** [comment] 2019-03-15 03:10
RCPTT appears to pay off. This seems to have caused regressions: https://tla.msr-inria.inria.fr/build/job/M-HEAD-master-Toolbox.product.standalone-mac/lastFailedBuild/testReport/junit/TEST-org.lamport.tla.toolbox.product/uitest/

**Comment by quaeler** [comment] 2019-03-15 04:04
will fix either the code or test, or appropriate to each test failure!

**Comment by quaeler** [comment] 2019-03-15 20:49
The failing tests are passing locally with https://github.com/quaeler/tlaplus/commit/34c6835790117a1cb726f0a1bd0a867eaf5ba708 the changes of substance for which tend to be checking to make sure the Run Model is disabled in most situations; additionally i added comments on a utility method, and standardized the spacing and comments in the test files i dealt with.

**Comment by quaeler** [comment] 2019-03-16 14:45
I believe build number 26 has passed due to this fix, so i'm re-closing this.

**Closed by quaeler** 2019-03-16 14:45 UTC
Labels: Toolbox, enhancement

**Comment by lemmy** [comment] 2019-03-16 18:11
There remain 6 test failures in the old UI test suite (SWTBot).  I restarted the builds on mac, win, and linux to check if they are just flukes.

**Comment by quaeler** [comment] 2019-03-24 19:03
As mentioned in an email thread, the SWTBot failures pass for me when run locally against `master` - in agreed further avoidance of the time drag here, i'm moving on to more #49 work.
